#pragma once

#ifndef DRAKOENGINE_COMPONENT_MEMORY_BYTES
# define DRAKOENGINE_COMPONENT_MEMORY_BYTES        10 * 1024 * 1024 // 10 MiB default
#endif
#ifndef DRAKOENGINE_STRING_MEMORY_BYTES
# define DRAKOENGINE_STRING_MEMORY_BYTES           10 * 1024 * 1024 // 10 MiB default
#endif

#ifndef DRAKOENGINE_DEFAULT_UNSIGNED_INTEGER_TYPE
# define DRAKOENGINE_DEFAULT_UNSIGNED_INTEGER_TYPE u64
#endif
#ifndef DRAKOENGINE_DEFAULT_SIGNED_INTEGER_TYPE
# define DRAKOENGINE_DEFAULT_SIGNED_INTEGER_TYPE   i64
#endif
#ifndef DRAKOENGINE_DEFAULT_FLOAT_TYPE
# define DRAKOENGINE_DEFAULT_FLOAT_TYPE            f64
#endif

namespace DrakoEngine {

    using UInt = DRAKOENGINE_DEFAULT_UNSIGNED_INTEGER_TYPE;
    using Int = DRAKOENGINE_DEFAULT_SIGNED_INTEGER_TYPE;
    using Float = DRAKOENGINE_DEFAULT_FLOAT_TYPE;

}
